name: typswift
description: Type where you want! You own your data.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  appflowy_editor: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  gap: ^3.0.1
  go_router: ^12.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/images/
  fonts:
    - family: Relative
      fonts:
        - asset: assets/fonts/Relative-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Relative-Bold.ttf
          style: normal
          weight: 700

flutter_icons:
  image_path: "assets/AppIcon.jpg"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/AppIcon.jpg"
  windows:
    generate: true
    image_path: "assets/Icon/app_icon_128.png"
    icon_size: 128
  macos: 
    generate: true
    image_path: "assets/Icon/app_icon_128.png"
  